baseurl = "/"
title = "Code Rood Netwerk"
copyright = ""
canonifyurls = true
languageCode = "nl-NL"
paginate = 3
theme = "coderood.clean"

googleAnalytics = ""
disqusShortname = ""

[author]
  name = ""

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[params]
  facebook = "coderoodnetwerk"
  email = "coderoodnetwerk@gmail.com"

[params.colors]
  # hugo-dusk colors
  background = "#999999" # background color for the site
  main = "#BB1133"
  text = "#111111"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color