name = "coderood"
license = "MIT"
licenselink = "https://github.com/gyorb/hugo-dusk/blob/master/LICENSE.md"
description = "Theme for coderood.net based on Hugo Dusk (https://github.com/gyorb/hugo-dusk)"
